name: Publish To Maven Central

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'

      - name: Set up Gradle cache
        uses: gradle/actions/setup-gradle@v4

      - name: Validate and build
        run: ./gradlew clean build --no-daemon

      - name: Publish and release on Maven Central
        run: ./gradlew publish closeAndReleaseSonatypeStagingRepository --no-daemon --stacktrace
        env:
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ vars.MAVEN_GPG_KEY_NAME }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.MAVEN_GPG_PASSWORD }}
